/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DriverProfile = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'totalTrips' : IDL.Nat,
  'tricyclePlate' : IDL.Text,
  'userId' : IDL.Principal,
  'isAvailable' : IDL.Bool,
  'tricycleModel' : IDL.Text,
  'earnings' : IDL.Float64,
  'licenseNumber' : IDL.Text,
  'rating' : IDL.Float64,
  'photoBlobId' : IDL.Opt(IDL.Text),
  'documentBlobId' : IDL.Opt(IDL.Text),
});
export const Rating = IDL.Record({
  'id' : IDL.Nat,
  'driverId' : IDL.Principal,
  'clientId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'tripId' : IDL.Nat,
  'score' : IDL.Nat,
  'comment' : IDL.Text,
});
export const TripStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'status' : TripStatus,
  'client' : IDL.Principal,
  'destination' : IDL.Text,
  'createdAt' : IDL.Int,
  'origin' : IDL.Text,
  'price' : IDL.Float64,
  'driver' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'tripId' : IDL.Nat,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'user' : IDL.Principal,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptTrip' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelTrip' : IDL.Func([IDL.Nat], [], []),
  'completeTrip' : IDL.Func([IDL.Nat], [], []),
  'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'getAllDriverProfiles' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
  'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientTrips' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DriverProfile)],
      ['query'],
    ),
  'getDriverRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getDriverTrips' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
  'getRevenueSummary' : IDL.Func([], [IDL.Float64], ['query']),
  'getTripMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getUserNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'requestTrip' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'startTrip' : IDL.Func([IDL.Nat], [], []),
  'submitRating' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateDriverProfile' : IDL.Func([DriverProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DriverProfile = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'totalTrips' : IDL.Nat,
    'tricyclePlate' : IDL.Text,
    'userId' : IDL.Principal,
    'isAvailable' : IDL.Bool,
    'tricycleModel' : IDL.Text,
    'earnings' : IDL.Float64,
    'licenseNumber' : IDL.Text,
    'rating' : IDL.Float64,
    'photoBlobId' : IDL.Opt(IDL.Text),
    'documentBlobId' : IDL.Opt(IDL.Text),
  });
  const Rating = IDL.Record({
    'id' : IDL.Nat,
    'driverId' : IDL.Principal,
    'clientId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'tripId' : IDL.Nat,
    'score' : IDL.Nat,
    'comment' : IDL.Text,
  });
  const TripStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'status' : TripStatus,
    'client' : IDL.Principal,
    'destination' : IDL.Text,
    'createdAt' : IDL.Int,
    'origin' : IDL.Text,
    'price' : IDL.Float64,
    'driver' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'tripId' : IDL.Nat,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'user' : IDL.Principal,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptTrip' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelTrip' : IDL.Func([IDL.Nat], [], []),
    'completeTrip' : IDL.Func([IDL.Nat], [], []),
    'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'getAllDriverProfiles' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
    'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientTrips' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'getDriverRatings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getDriverTrips' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
    'getRevenueSummary' : IDL.Func([], [IDL.Float64], ['query']),
    'getTripMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getUserNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'requestTrip' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'startTrip' : IDL.Func([IDL.Nat], [], []),
    'submitRating' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateDriverProfile' : IDL.Func([DriverProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };