/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DriverProfile {
  'lat' : number,
  'lng' : number,
  'totalTrips' : bigint,
  'tricyclePlate' : string,
  'userId' : Principal,
  'isAvailable' : boolean,
  'tricycleModel' : string,
  'earnings' : number,
  'licenseNumber' : string,
  'rating' : number,
  'photoBlobId' : [] | [string],
  'documentBlobId' : [] | [string],
}
export interface Message {
  'id' : bigint,
  'createdAt' : bigint,
  'tripId' : bigint,
  'sender' : Principal,
  'message' : string,
}
export interface Notification {
  'id' : bigint,
  'createdAt' : bigint,
  'read' : boolean,
  'user' : Principal,
  'message' : string,
}
export interface Rating {
  'id' : bigint,
  'driverId' : Principal,
  'clientId' : Principal,
  'createdAt' : bigint,
  'tripId' : bigint,
  'score' : bigint,
  'comment' : string,
}
export interface Trip {
  'id' : bigint,
  'status' : TripStatus,
  'client' : Principal,
  'destination' : string,
  'createdAt' : bigint,
  'origin' : string,
  'price' : number,
  'driver' : Principal,
}
export type TripStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'userId' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'email' : string,
  'loyaltyPoints' : bigint,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptTrip' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelTrip' : ActorMethod<[bigint], undefined>,
  'completeTrip' : ActorMethod<[bigint], undefined>,
  'createNotification' : ActorMethod<[Principal, string], bigint>,
  'getAllDriverProfiles' : ActorMethod<[], Array<DriverProfile>>,
  'getAllRatings' : ActorMethod<[], Array<Rating>>,
  'getAllTrips' : ActorMethod<[], Array<Trip>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientTrips' : ActorMethod<[Principal], Array<Trip>>,
  'getCurrentUserRole' : ActorMethod<[], UserRole>,
  'getDriverProfile' : ActorMethod<[Principal], [] | [DriverProfile]>,
  'getDriverRatings' : ActorMethod<[Principal], Array<Rating>>,
  'getDriverTrips' : ActorMethod<[Principal], Array<Trip>>,
  'getRevenueSummary' : ActorMethod<[], number>,
  'getTripMessages' : ActorMethod<[bigint], Array<Message>>,
  'getUserNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'requestTrip' : ActorMethod<[string, number], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], bigint>,
  'startTrip' : ActorMethod<[bigint], undefined>,
  'submitRating' : ActorMethod<[bigint, Principal, bigint, string], bigint>,
  'updateDriverProfile' : ActorMethod<[DriverProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];